"""Regenerate paper/numbers.md from results/processed/.

Every figure the paper quotes comes from here, so a grown dataset is a re-run
rather than a re-typing. Nothing in numbers.md is hand-entered.

    python paper/make_numbers.py
"""
from __future__ import annotations

import itertools
import json
import os
import sys

import numpy as np
import pandas as pd
from scipy.stats import kendalltau, spearmanr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
P = os.path.join(ROOT, "results", "processed")


def load(name):
    return pd.read_parquet(os.path.join(P, name))


rows = load("rows.parquet")
cells = load("cells.parquet")
spread = load("spread.parquet")
stab = load("stability.parquet")
da = load("dispatch_audit.parquet")
inv = load("inversions.parquet")
oc = load("oom_calibration.parquet")
cs = load("cache_sensitivity.parquet")
summ = json.load(open(os.path.join(P, "summary.json"), encoding="utf8"))
sel = json.load(open(os.path.join(P, "selector.json"), encoding="utf8"))
env = summ["environment"]

cells["regime"] = cells.cell.str.split("|").str[0]
GPUS = sorted(cells.gpu_name.unique())
SHORT = {"NVIDIA A10": "A10", "NVIDIA A100-SXM4-80GB": "A100",
         "NVIDIA H100 80GB HBM3": "H100", "NVIDIA L40": "L40",
         "NVIDIA L40S": "L40S"}
STRIP = ("D1-inductor", "P1-inductor-nofuse", "P1-inductor-where")
PRACTICAL = 1.10

O = []
w = O.append


def sh(g):
    return SHORT.get(g, g)


def table(head, body):
    # Cell keys contain "|", and GFM splits a row on pipes before it parses
    # inline code -- an unescaped cell key silently shatters the whole table
    # into extra columns.
    esc = lambda x: str(x).replace("|", "\\|")
    w("| " + " | ".join(esc(h) for h in head) + " |")
    w("|" + "|".join("---" for _ in head) + "|")
    for r in body:
        w("| " + " | ".join(esc(x) for x in r) + " |")
    w("")


def thin(n, lim=50):
    return " **(thin: n<%d)**" % lim if n < lim else ""


# --------------------------------------------------------------------------- #
# Shared derivations
# --------------------------------------------------------------------------- #

W = cells.loc[cells.groupby(["gpu_name", "cell"]).median_us.idxmin()]
piv = {g: cells[cells.gpu_name == g].set_index(["cell", "implementation"]).median_us
       for g in GPUS}
union = rows.groupby("regime").cell.nunique().to_dict()


def flip(gset, regime=None):
    """(n shared cells, fraction where the winner is not the same impl)."""
    v = W[W.gpu_name.isin(gset)]
    if regime:
        v = v[v.regime == regime]
    n = v.groupby("cell").gpu_name.nunique()
    v = v[v.cell.isin(n[n == len(gset)].index)]
    per = v.groupby("cell").implementation.nunique()
    return len(per), (float((per > 1).mean()) if len(per) else float("nan"))


def pairwise(a, b):
    """Spearman/Kendall medians and the exact impl-pair denominator."""
    rs, ks, npairs, shared = [], [], 0, 0
    ca = set(cells[cells.gpu_name == a].cell)
    cb = set(cells[cells.gpu_name == b].cell)
    for cell in sorted(ca & cb):
        shared += 1
        s1, s2 = piv[a].loc[cell], piv[b].loc[cell]
        com = sorted(set(s1.index) & set(s2.index))
        npairs += len(com) * (len(com) - 1) // 2
        if len(com) < 3:
            continue
        rs.append(spearmanr(s1[com], s2[com]).statistic)
        ks.append(kendalltau(s1[com], s2[com]).statistic)
    d = inv[((inv.gpu_a == a) & (inv.gpu_b == b))
            | ((inv.gpu_a == b) & (inv.gpu_b == a))]
    return dict(shared=shared, n_rho=len(rs),
                spearman=float(np.nanmedian(rs)) if rs else np.nan,
                kendall=float(np.nanmedian(ks)) if ks else np.nan,
                pairs=npairs, practical=int(d.practical.sum()),
                sig=int(d.sig.sum()), stored=int(d.pairs_examined.max())
                if len(d) else 0)


PW = {(a, b): pairwise(a, b) for a, b in itertools.combinations(GPUS, 2)}

# --------------------------------------------------------------------------- #
# Header
# --------------------------------------------------------------------------- #

v = env["NVIDIA H100 80GB HBM3"]["versions"]
w("# Numbers for the paper")
w("")
w("Generated by `paper/make_numbers.py` from `results/processed/`. "
  "Do not hand-edit -- re-run the script.")
w("")
w("Every figure states the **n** it rests on. Any n below 50 cells is flagged "
  "inline. The final section lists what is **not** safe to quote and why.")
w("")
w("Software-distribution snapshot on every row: torch %s, CUDA %s, triton %s, "
  "flash-attn %s, flashinfer %s."
  % (v["torch"], v["cuda"], v["triton"], v["flash_attn"], v["flashinfer"]))
w("")
w("A **cell** is one configuration key "
  "`regime|B|Hq|Hkv|D|N|dtype|mode|launch|cache|causal`. Every claim below is "
  "scoped to a **(kernel, GPU, regime, software-distribution snapshot)**, "
  "never to a (kernel, GPU, regime) alone.")
w("")

# --------------------------------------------------------------------------- #
# 1. Dataset
# --------------------------------------------------------------------------- #

w("## 1. Dataset")
w("")
t = rows.groupby(["gpu_name", "regime"]).agg(
    n_rows=("cell", "size"), n_cells=("cell", "nunique"),
    n_impls=("implementation", "nunique"),
    n_repeats=("repeat", "nunique")).reset_index()
t["expected"] = t.n_cells * t.n_impls * t.n_repeats
t["completeness"] = t.n_rows / t.expected

w("`expected = cells x implementations x process repeats` for that device; "
  "completeness is measured rows over that. `grid coverage` is that device's "
  "cell count against the union grid measured anywhere (%d prefill cells, "
  "%d decode cells)." % (union["prefill"], union["decode"]))
w("")
table(["GPU", "regime", "rows", "cells", "impls", "process repeats",
       "expected rows", "completeness", "grid coverage"],
      [[sh(r.gpu_name), r.regime, r.n_rows, r.n_cells, r.n_impls, r.n_repeats,
        r.expected, "%.3f" % r.completeness,
        "%d/%d = %.3f" % (r.n_cells, union[r.regime],
                          r.n_cells / union[r.regime])]
       for r in t.itertuples()])

w("Rows surviving `usable()` -- status OK, no erratic throttle bit set, "
  "correctness gate class not failed -- collapsed to one median per "
  "(GPU, cell, implementation). This triple is the unit every ranking below "
  "is computed on.")
w("")
us = cells.groupby(["gpu_name", "regime"]).agg(
    triples=("cell", "size"), n_cells=("cell", "nunique"),
    impls=("implementation", "nunique")).reset_index()
table(["GPU", "regime", "usable (GPU,cell,impl) triples", "cells", "impls"],
      [[sh(r.gpu_name), r.regime, r.triples, r.n_cells, r.impls]
       for r in us.itertuples()])

attempted = len(rows.groupby(["gpu_name", "cell", "implementation"]))
table(["quantity", "value", "how"],
      [["measured rows", len(rows), "`len(rows.parquet)`"],
       ["distinct cells (union of both regimes)", rows.cell.nunique(),
        "`rows.cell.nunique()`"],
       ["(GPU, cell, impl) triples attempted", attempted,
        "groupby on rows.parquet"],
       ["(GPU, cell, impl) triples usable", len(cells),
        "`len(cells.parquet)` = %.1f%% of attempted"
        % (100 * len(cells) / attempted)],
       ["devices with measured rows", len(GPUS),
        ", ".join(sh(g) for g in GPUS)],
       ["compute capabilities covered",
        len({(env[g]["cc_major"], env[g]["cc_minor"]) for g in GPUS}),
        ", ".join(sorted({"%d.%d" % (env[g]["cc_major"], env[g]["cc_minor"])
                          for g in GPUS}))],
       ["prefill implementations",
        rows[rows.regime == "prefill"].implementation.nunique(),
        "P0/P1x3/P2bx1/P2c/P2d/P3/P4/P4h"],
       ["decode implementations",
        rows[rows.regime == "decode"].implementation.nunique(),
        "D0/D1/D2/D3/D4/D6"]])

reps = t.set_index(["gpu_name", "regime"]).n_repeats
w("**Caveat on '5 process repeats x 30 reps'.** Five process-level repeats "
  "hold on A10 (both regimes), A100 decode and H100 (both regimes) only. "
  "A100 prefill has %d, L40 has %d, L40S has %d. Quote the per-device repeat "
  "count from the table above, never a blanket 5."
  % (reps[("NVIDIA A100-SXM4-80GB", "prefill")],
     reps[("NVIDIA L40", "prefill")], reps[("NVIDIA L40S", "prefill")]))
w("")

# --------------------------------------------------------------------------- #
# 2. Hardware
# --------------------------------------------------------------------------- #

w("## 2. Hardware")
w("")
shas = rows.groupby("gpu_name").git_sha.unique()
table(["GPU", "cc", "SMs", "memory (GB)", "L2 (MiB)",
       "measured peak BW (GB/s)", "event overhead (us)", "driver (manifest)",
       "git sha(s) carrying rows"],
      [[sh(g), "%d.%d" % (env[g]["cc_major"], env[g]["cc_minor"]),
        env[g]["sm_count"], "%.2f" % env[g]["total_memory_gb"],
        "%.0f" % (env[g]["l2_bytes"] / 2 ** 20),
        "%.1f" % env[g]["measured_peak_bw_gbs"],
        "%.3f" % env[g]["event_overhead_us"], env[g]["driver"],
        " + ".join(s[:8] for s in sorted(shas[g]))] for g in GPUS])

w("Bandwidth is **measured** in-process, not vendor-quoted: "
  "`theoretical_bw_gbs` is null for every device, so no roofline figure in "
  "this paper is a datasheet number.")
w("")
w("Event-timer overhead is the floor under every latency on that device. The "
  "table below is the headroom each device actually has -- its fastest usable "
  "measurement against its own overhead. **H100 is the tight one**: its "
  "fastest cell is only %.1fx its event overhead, and %d of its %d usable "
  "triples sit within 5x of it. Sub-20 us H100 decode latencies should carry "
  "that caveat."
  % (cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"].median_us.min()
     / env["NVIDIA H100 80GB HBM3"]["event_overhead_us"],
     int((cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"].median_us
          < 5 * env["NVIDIA H100 80GB HBM3"]["event_overhead_us"]).sum()),
     int((cells.gpu_name == "NVIDIA H100 80GB HBM3").sum())))
w("")
table(["GPU", "event overhead (us)", "fastest usable median (us)",
       "headroom", "triples within 5x of overhead", "of n triples"],
      [[sh(g), "%.3f" % env[g]["event_overhead_us"],
        "%.2f" % cells[cells.gpu_name == g].median_us.min(),
        "%.1fx" % (cells[cells.gpu_name == g].median_us.min()
                   / env[g]["event_overhead_us"]),
        int((cells[cells.gpu_name == g].median_us
             < 5 * env[g]["event_overhead_us"]).sum()),
        int((cells.gpu_name == g).sum())] for g in GPUS])
w("**Driver is a per-device manifest field, not a per-run one.** The manifest "
  "records one driver per device, written by the last process to touch it. "
  "A10 and A100 each carry rows from two commits recorded on different days, "
  "so their manifest driver is the later one and cannot be attributed to the "
  "earlier rows.")
w("")
ok_dec = rows[(rows.status == "OK") & (rows.regime == "decode")]
bw = ok_dec.groupby("gpu_name").agg(n=("bw_util", "count"),
                                    med=("bw_util", "median"),
                                    p95=("bw_util", lambda s: s.quantile(.95)))
w("Median decode bandwidth utilisation -- effective KV traffic divided by that "
  "device's measured peak. Prefill is not bandwidth-bound, so it has none.")
w("")
table(["GPU", "n decode OK rows", "median bw_util", "p95 bw_util"],
      [[sh(g), int(bw.n[g]), "%.3f" % bw.med[g], "%.3f" % bw.p95[g]]
       for g in bw.index])
w("**L40's median exceeds 1.0 (%.3f)**, so its measured-peak probe under-reads "
  "what the decode kernels actually sustain on that part. Do not quote an L40 "
  "utilisation as a fraction of achievable bandwidth."
  % bw.med["NVIDIA L40"])
w("")
extra = sorted(set(env) - set(GPUS))
w("`%s` has an environment manifest (cc %d.%d, %d SMs, %.0f GB/s measured) but "
  "**zero benchmark rows**. It is not a device in this study."
  % (extra[0], env[extra[0]]["cc_major"], env[extra[0]]["cc_minor"],
     env[extra[0]]["sm_count"], env[extra[0]]["measured_peak_bw_gbs"]))
w("")

# --------------------------------------------------------------------------- #
# 3. Portability headline
# --------------------------------------------------------------------------- #

w("## 3. Portability headline: winner-flip rate")
w("")
w("Winner = argmin median_us over the implementations that produced a usable "
  "measurement in that (device, cell). A set's flip rate is computed only on "
  "cells **every device in the set ran**, and counts the cells where the "
  "winner is not the same implementation on all of them.")
w("")
w("> **A flip rate is only comparable within a fixed n_gpus.** More devices "
  "means more chances to disagree, so the rate rises mechanically with device "
  "count. Every row is labelled with n_gpus and n_cells for exactly that "
  "reason; never quote one row against another with a different n_gpus.")
w("")
TRI = ["NVIDIA A10", "NVIDIA A100-SXM4-80GB", "NVIDIA H100 80GB HBM3"]
sets = [("all 5 devices", GPUS),
        ("A10/A100/H100/L40", TRI + ["NVIDIA L40"]),
        ("A10/A100/H100", TRI)]
sets += [("/".join(sh(x) for x in p), list(p))
         for p in itertools.combinations(GPUS, 2)]
body = []
for lbl, gs in sets:
    for r in ("prefill", "decode", None):
        n, f = flip(gs, r)
        if not n:
            continue
        body.append([lbl, len(gs), r or "both pooled", n,
                     "%.1f%%" % (100 * f), "%.1f%%" % (100 * (1 - f))])
table(["GPU set", "n_gpus", "regime", "n_cells (shared)",
       "winner-flip rate", "top-1 stable"], body)
w("No row here falls under the n<50 threshold; the smallest shared set is "
  "n=%d cells (all 5 devices, and A100 vs L40S)." % min(r[3] for r in body))
w("")

n_ah, f_ah = flip(["NVIDIA A10", "NVIDIA H100 80GB HBM3"], "prefill")
n_td, f_td = flip(TRI, "decode")
n_tp, f_tp = flip(TRI)
n_all, f_all = flip(GPUS)
w("Headline sentences that are safe, each carrying its own n_gpus and n:")
w("")
w("- **Prefill, A10 vs H100** (n_gpus=2, n_cells=%d): the fastest "
  "implementation changes on **%.1f%%** of matched cells." % (n_ah, 100 * f_ah))
w("- **Decode, A10/A100/H100** (n_gpus=3, n_cells=%d): **%.1f%%**. This one is "
  "confounded -- see the not-safe section." % (n_td, 100 * f_td))
w("- **Both regimes pooled, A10/A100/H100** (n_gpus=3, n_cells=%d): **%.1f%%**."
  % (n_tp, 100 * f_tp))
w("- **All 5 devices** (n_gpus=5, n_cells=%d, **prefill only** -- L40S ran no "
  "decode): **%.1f%%**. Must be labelled prefill-only and is not comparable "
  "to the 3-device figure." % (n_all, 100 * f_all))
w("")

# --------------------------------------------------------------------------- #
# 4. Pairwise
# --------------------------------------------------------------------------- #

w("## 4. Pairwise agreement")
w("")
w("Spearman/Kendall: within each shared cell, rank the implementations both "
  "devices ran (>=3 in common required), then take the median correlation "
  "across cells. **Practical inversion**: an implementation pair (a,b) whose "
  "order flips between the devices *and* is at least %.2fx apart on both -- "
  "counted over every implementation pair examined on shared cells. "
  "**Statistical inversion** additionally requires both cluster-bootstrap CIs "
  "to exclude 1." % PRACTICAL)
w("")
table(["pair", "shared cells", "cells with >=3 common impls",
       "Spearman (median)", "Kendall (median)", "impl pairs examined",
       "practical inv.", "practical rate", "statistical inv.",
       "statistical rate"],
      [["%s vs %s" % (sh(a), sh(b)), d["shared"], d["n_rho"],
        "%.3f" % d["spearman"], "%.3f" % d["kendall"], d["pairs"],
        d["practical"], "%.2f%%" % (100 * d["practical"] / d["pairs"]),
        d["sig"], "%.2f%%" % (100 * d["sig"] / d["pairs"])]
       for (a, b), d in PW.items()])
w("Smallest pair here is n=%d shared cells (A100 vs L40S), so no row falls "
  "under the n<50 threshold -- but the three L40S pairs rest on roughly a "
  "third the cells of the others and are prefill-only."
  % min(d["shared"] for d in PW.values()))
w("")

ctl = PW[("NVIDIA L40", "NVIDIA L40S")]
bw_gap = 100 * abs(env["NVIDIA L40S"]["measured_peak_bw_gbs"]
                   / env["NVIDIA L40"]["measured_peak_bw_gbs"] - 1)
w("### Same-architecture control (the noise floor)")
w("")
w("L40 and L40S are both sm%d%d, %d SMs, %d MiB L2, with measured bandwidth "
  "%.1f and %.1f GB/s -- **%.1f%% apart**. They still disagree: Spearman "
  "**%.3f** and **%.2f%%** practical inversions over %d shared cells and %d "
  "implementation pairs. **No cross-architecture inversion rate at or below "
  "this floor is evidence of anything.**"
  % (env["NVIDIA L40"]["cc_major"], env["NVIDIA L40"]["cc_minor"],
     env["NVIDIA L40"]["sm_count"],
     env["NVIDIA L40"]["l2_bytes"] // 2 ** 20,
     env["NVIDIA L40"]["measured_peak_bw_gbs"],
     env["NVIDIA L40S"]["measured_peak_bw_gbs"], bw_gap,
     ctl["spearman"], 100 * ctl["practical"] / ctl["pairs"], ctl["shared"],
     ctl["pairs"]))
w("")
w("Both devices ran **prefill only**, so this floor is calibrated for prefill "
  "and is not established for decode.")
w("")
below = [(a, b, d) for (a, b), d in PW.items()
         if d["practical"] / d["pairs"] <= ctl["practical"] / ctl["pairs"]
         and (a, b) != ("NVIDIA L40", "NVIDIA L40S")]
w("Pairs at or below the floor: %s. Those are not usable as portability "
  "evidence."
  % (", ".join("%s vs %s (%.2f%%)" % (sh(a), sh(b),
                                      100 * d["practical"] / d["pairs"])
               for a, b, d in below) or "none"))
w("")
drift = max(abs(d["pairs"] - d["stored"]) for d in PW.values())
w("`inversions.parquet` stores `pairs_examined` as a running counter written "
  "only onto inverting pairs, so its maximum undercounts the true denominator "
  "slightly. The denominators above are recomputed exactly from "
  "`cells.parquet`; they differ from the stored maxima by at most %d pairs "
  "(<%.2f%%), which moves no rate in the third decimal."
  % (drift, 100 * drift / min(d["pairs"] for d in PW.values())))
w("")

# --------------------------------------------------------------------------- #
# 5. Per-device winners
# --------------------------------------------------------------------------- #

w("## 5. Per-device winners")
w("")
for regime in ("prefill", "decode"):
    sub = W[W.regime == regime]
    gs = [g for g in GPUS if len(sub[sub.gpu_name == g])]
    w("### %s: wins per implementation, over all cells that device ran"
      % regime.capitalize())
    w("")
    body = [[i] + [int(((sub.gpu_name == g) & (sub.implementation == i)).sum())
                   for g in gs]
            for i in sorted(sub.implementation.unique())]
    body.append(["**n_cells**"] + ["**%d**" % len(sub[sub.gpu_name == g])
                                   for g in gs])
    table(["implementation"] + [sh(g) for g in gs], body)
w("Columns are **not matched**: each device ran a different number of cells. "
  "For a like-for-like statement use the matched subset below.")
w("")
for regime in ("prefill", "decode"):
    pair = ("NVIDIA A10", "NVIDIA H100 80GB HBM3")
    sub = W[W.gpu_name.isin(pair) & (W.regime == regime)]
    n = sub.groupby("cell").gpu_name.nunique()
    sub = sub[sub.cell.isin(n[n == 2].index)]
    if sub.empty:
        continue
    w("### %s, matched %s vs %s (n_cells=%d)"
      % (regime.capitalize(), sh(pair[0]), sh(pair[1]), sub.cell.nunique()))
    w("")
    body = []
    for i in sorted(sub.implementation.unique()):
        x = int(((sub.gpu_name == pair[0]) & (sub.implementation == i)).sum())
        y = int(((sub.gpu_name == pair[1]) & (sub.implementation == i)).sum())
        body.append([i, x, y, "%+d" % (y - x)])
    table(["implementation", sh(pair[0]), sh(pair[1]), "change"], body)
w("P4h-fa3 wins only where it can run: it is UNSUPPORTED on every device that "
  "is not sm90 (section 7), so its zero on A10/A100/L40/L40S is a coverage "
  "fact, not a performance result. The same reading applies in reverse to any "
  "implementation absent from a device's column.")
w("")

# --------------------------------------------------------------------------- #
# 6. Spread
# --------------------------------------------------------------------------- #

w("## 6. Spread (slowest / fastest implementation within a cell)")
w("")
w("Spread = `max(median_us) / min(median_us)` over the implementations that "
  "produced a usable measurement in that (device, cell). It therefore depends "
  "on **which** implementations survived there, not only on how far apart they "
  "are, so the median implementation count per cell travels with it.")
w("")
q = lambda p: (lambda s: s.quantile(p))
byr = spread.groupby("regime").spread.agg(n="size", median="median",
                                          p90=q(.9), p95=q(.95), max="max")
table(["regime", "n (device,cell) pairs", "median spread", "p90", "p95", "max"],
      [[r, int(byr.n[r]), "%.2fx" % byr["median"][r], "%.1fx" % byr.p90[r],
        "%.1fx" % byr.p95[r], "%.1fx" % byr["max"][r]] for r in byr.index])

nimp = cells.groupby(["gpu_name", "cell"]).size()
byg = spread.groupby(["gpu_name", "regime"]).spread.agg(
    n="size", median="median", p95=q(.95), max="max")
body = []
for (g, r), row in byg.iterrows():
    m = np.median([n for (gg, cc), n in nimp.items()
                   if gg == g and cc.startswith(r)])
    body.append([sh(g), r, int(row["n"]), "%.2fx" % row["median"],
                 "%.1fx" % row["p95"], "%.1fx" % row["max"], "%.1f" % m])
table(["GPU", "regime", "n cells", "median spread", "p95", "max",
       "median impls per cell"], body)

w("Safe headline: **prefill spread is a median %.1fx, decode %.2fx** "
  "(n=%d and n=%d device-cell pairs). Read it as 'the choice of "
  "implementation matters roughly %.1fx more in prefill than in decode', not "
  "as one kernel being %.0fx faster than another everywhere."
  % (byr["median"]["prefill"], byr["median"]["decode"],
     int(byr.n["prefill"]), int(byr.n["decode"]),
     byr["median"]["prefill"] / byr["median"]["decode"],
     byr["median"]["prefill"]))
w("")
w("Absolute anchors, so no spread is ever quoted as a bare ratio:")
w("")
table(["regime", "n triples", "fastest", "p25", "median", "p75", "slowest"],
      [[r, int((cells.regime == r).sum())]
       + ["%.1f us" % x if x < 1e6 else "%.2f s" % (x / 1e6)
          for x in (cells[cells.regime == r].median_us.min(),
                    cells[cells.regime == r].median_us.quantile(.25),
                    cells[cells.regime == r].median_us.median(),
                    cells[cells.regime == r].median_us.quantile(.75),
                    cells[cells.regime == r].median_us.max())]
       for r in ("prefill", "decode")])
slow = cells.loc[cells[cells.regime == "prefill"].median_us.idxmax()]
w("The prefill tail is the `fwd_bwd` end of the grid, not the naive kernel: "
  "the slowest usable measurement in the dataset is **%s on %s at %.2f s** "
  "(`%s`). Quote a spread beside the pair of latencies it came from, never on "
  "its own."
  % (slow.implementation, sh(slow.gpu_name), slow.median_us / 1e6, slow.cell))
w("")

# --------------------------------------------------------------------------- #
# 7. Status taxonomy
# --------------------------------------------------------------------------- #

w("## 7. Status taxonomy")
w("")
w("These are **kinds of outcome, not severities**. A row is exactly one of "
  "them and they are not ordered: an UNSUPPORTED row is not a worse OK, and "
  "an OOM_PREDICTED row is not a failed OOM.")
w("")
table(["status", "meaning", "written when", "n rows", "share"],
      [["OK", "The cell was built, ran, passed the correctness gate for its "
        "equivalence class, and was timed. **Only these rows enter any "
        "ranking.**", "the measurement completed",
        int((rows.status == "OK").sum()),
        "%.1f%%" % (100 * (rows.status == "OK").mean())],
       ["UNSUPPORTED", "The implementation declined this (config, device). "
        "Either the kernel does not exist for this compute capability or "
        "shape, **or** the config lies outside the strip this implementation "
        "is deliberately run on. Not a failure and not a crash.",
        "`impl.supports()` false, `impl_applies()` false, "
        "`NotImplementedError`, or a `RuntimeError` naming 'No available "
        "kernel' / 'not supported'",
        int((rows.status == "UNSUPPORTED").sum()),
        "%.1f%%" % (100 * (rows.status == "UNSUPPORTED").mean())],
       ["OOM_PREDICTED", "The allocation was computed in advance to exceed the "
        "device and the cell was **refused, never attempted**. No timing "
        "exists and no OOM was provoked.",
        "`oom_predicted_bytes()` returned non-zero",
        int((rows.status == "OOM_PREDICTED").sum()),
        "%.1f%%" % (100 * (rows.status == "OOM_PREDICTED").mean())],
       ["OOM", "The cell **was** attempted and the allocator raised "
        "`torch.cuda.OutOfMemoryError`. The predictor missed it.",
        "caught at run time", int((rows.status == "OOM").sum()),
        "%.1f%%" % (100 * (rows.status == "OOM").mean())]])
w("`NUMERICAL_FAIL` and `ERROR` are defined in `akp/run.py` but **occur zero "
  "times** in this dataset. Every implementation that ran, ran correctly.")
w("")

u = rows[rows.status == "UNSUPPORTED"]
w("**UNSUPPORTED conflates two unrelated things** and must never be reported "
  "as a single number:")
w("")
table(["kind", "n rows", "share of UNSUPPORTED", "which"],
      [["outside the deliberate strip (a sampling decision, not a capability "
        "limit)", int(u.implementation.isin(STRIP).sum()),
        "%.1f%%" % (100 * u.implementation.isin(STRIP).mean()),
        "`%s` are run only on a narrow slice of the grid; every other config "
        "is recorded UNSUPPORTED by `impl_applies()`" % "`, `".join(STRIP)],
       ["genuine capability gap", int((~u.implementation.isin(STRIP)).sum()),
        "%.1f%%" % (100 * (~u.implementation.isin(STRIP)).mean()),
        "P4h-fa3 off sm90 (%d rows, every non-H100 device) and "
        "P2b-sdpa-mem-eff on H100 (%d rows, all carrying "
        "'RuntimeError: No available kernel')"
        % (int((u.implementation == "P4h-fa3").sum()),
           int((u.implementation == "P2b-sdpa-mem-eff").sum()))]])

w("Per implementation per device, as `OK / UNSUPPORTED / OOM_PREDICTED / OOM`. "
  "A dash means the device never attempted that implementation (the decode "
  "implementations on L40S, which ran prefill only).")
w("")
ct = pd.crosstab([rows.implementation, rows.gpu_name], rows.status)
for c in ("OK", "UNSUPPORTED", "OOM_PREDICTED", "OOM"):
    if c not in ct:
        ct[c] = 0
body = []
for i in sorted(rows.implementation.unique()):
    r = [i + (" *(strip)*" if i in STRIP else "")]
    for g in GPUS:
        if (i, g) not in ct.index:
            r.append("--")
        else:
            x = ct.loc[(i, g)]
            r.append("%d / %d / %d / %d"
                     % (x.OK, x.UNSUPPORTED, x.OOM_PREDICTED, x.OOM))
    body.append(r)
table(["implementation"] + [sh(g) for g in GPUS], body)

ok = oc[oc.status == "OK"].copy()
ok["m"] = ok.cell.str.split("|").str[7]
w("**OOM_PREDICTED is a refusal, so the predictor has no ground truth on the "
  "cells it refused.** Recomputing the same prediction on the score-matrix "
  "cells that did run gives predicted/actual peak memory of **%.2f** median on "
  "`fwd` (n=%d) and **%.2f** on `fwd_bwd` (n=%d). The predictor models the "
  "forward score matrix only, so it under-predicts `fwd_bwd` by construction. "
  "%d cells were refused and carry no actual; %d cells OOMed anyway despite "
  "passing the predictor."
  % (ok[ok.m == "fwd"].ratio.median(), int((ok.m == "fwd").sum()),
     ok[ok.m == "fwd_bwd"].ratio.median(), int((ok.m == "fwd_bwd").sum()),
     int((oc.status == "OOM_PREDICTED").sum()),
     int((rows.status == "OOM").sum())))
w("")
w("The %d OOM rows are: %s. All of them are cells the predictor let through."
  % (int((rows.status == "OOM").sum()),
     "; ".join("%s on %s (%d)" % (i, sh(g), n) for (i, g), n
               in rows[rows.status == "OOM"]
               .groupby(["implementation", "gpu_name"]).size().items())))
w("")

# --------------------------------------------------------------------------- #
# 8. Dispatch
# --------------------------------------------------------------------------- #

w("## 8. Dispatch audit")
w("")
pr = da[da.probed]
nc = da.dispatch_class.nunique()
cov = pr.dispatch_class.nunique()
mism = int((pr.matched == False).sum())  # noqa: E712 -- object column
table(["quantity", "value", "how"],
      [["audited rows", len(da), "every `status == OK` row"],
       ["rows with a readable kernel trace (probed)",
        "%d (%.1f%%)" % (int(da.probed.sum()), 100 * da.probed.mean()),
        "a non-empty trace not starting with `<`"],
       ["probe failures (unprobed)", int((~da.probed).sum()),
        "no trace captured; counted as unknown, **never** as a mismatch"],
       ["dispatch classes", nc,
        "(impl, GPU, head_dim, dtype, gqa, mode, launch) -- the unit a "
        "dispatch answer is actually about, since the launched kernel is not a "
        "function of batch or length"],
       ["classes with >=1 probed row",
        "%d (%.2f%%)" % (cov, 100 * cov / nc), "**probe coverage**"],
       ["**mismatch rate among probed rows**",
        "**%.3f%%** (%d of %d)" % (100 * mism / len(pr), mism, len(pr)),
        "requested kernel family absent from the trace"],
       ["mismatch rate over all audited rows",
        "%.3f%% (%d of %d)" % (100 * mism / len(da), mism, len(da)),
        "same numerator, larger denominator -- **state which you mean**"]])
w("Mismatches concentrate rather than spreading across the stack: %s."
  % "; ".join("%s on %s (%d)" % (i, sh(g), n) for (i, g), n
              in pr[pr.matched == False]  # noqa: E712
              .groupby(["implementation", "gpu_name"]).size().items()))
w("")

ind = rows[rows.implementation.str.startswith(("P1-", "D1-"))]
indok = ind[ind.fuse_attention.notna()]
t45 = da[da.attn_kernel_in_trace]
w("### TorchInductor's `fuse_attention` counter")
w("")
table(["quantity", "value"],
      [["inductor rows in the dataset (P1-*, D1-*)", len(ind)],
       ["inductor rows that ran and captured the counter", len(indok)],
       ["of those, `fuse_attention > 0`",
        int((indok.fuse_attention > 0).sum())],
       ["maximum value observed anywhere",
        "%.0f" % indok.fuse_attention.max()],
       ["devices covered", "%d (%s)" % (indok.gpu_name.nunique(),
                                        ", ".join(sh(g) for g in
                                                  sorted(indok.gpu_name.unique())))],
       ["`fused_into_sdpa` true in `dispatch_audit`",
        int(da.fused_into_sdpa.sum())]])
w("**Safe claim:** on all %d inductor rows that captured the counter, across "
  "all %d devices, `fuse_attention` is 0. `torch.compile` never fired its "
  "attention-fusion pattern on this naive attention source under this "
  "software-distribution snapshot."
  % (len(indok), indok.gpu_name.nunique()))
w("")
fl_p1 = int(((pr.implementation == "P1-inductor")
             & (pr.observed == "pytorch-flash")).sum())
fl_pw = int(((pr.implementation == "P1-inductor-where")
             & (pr.observed == "pytorch-flash")).sum())
w("**The counter is not the whole story, and the stronger claim does not "
  "hold.** %d probed inductor rows *do* carry a flash kernel in their trace "
  "(`attn_kernel_in_trace`), all on %s, all in %s, over %d distinct cells. "
  "Separately, %d P1-inductor and %d P1-inductor-where probed rows report an "
  "observed backend of `pytorch-flash` rather than `triton`. The honest "
  "wording is **'Inductor's own fusion counter never fired'**, not 'no SDPA "
  "kernel ever appeared in a compiled path'."
  % (len(t45), ", ".join(sh(g) for g in sorted(t45.gpu_name.unique())),
     " and ".join(sorted(t45.implementation.unique())), t45.cell.nunique(),
     fl_p1, fl_pw))
w("")
w("Observed backend per implementation, probed rows only. This is what "
  "actually ran, independent of what was requested.")
w("")
ob = pr.groupby(["implementation", "observed"]).size()
table(["implementation", "observed backends (n probed rows)"],
      [[i, ", ".join("`%s` %d" % (o, n)
                     for o, n in ob[i].sort_values(ascending=False).items())]
       for i in sorted(pr.implementation.unique())])

# --------------------------------------------------------------------------- #
# 9. Selector
# --------------------------------------------------------------------------- #

w("## 9. Hardware-aware selector")
w("")
from akp import analysis as A  # noqa: E402 -- after the data loads

meta = {g: {"cc": float("%d.%d" % (m["cc_major"], m["cc_minor"])),
            "bw": m["measured_peak_bw_gbs"]} for g, m in env.items()}
best = A.winners(cells).set_index(["gpu_name", "cell"])
lat = cells.set_index(["gpu_name", "cell", "implementation"]).median_us
tbl = best.reset_index()
tbl = tbl.join(A.features(tbl, meta))
fit = tbl[tbl.gpu_name.str.contains("|".join(A.FIT_GPUS))]
hold = tbl[~tbl.gpu_name.str.contains("|".join(A.FIT_GPUS))]
from sklearn.tree import DecisionTreeClassifier  # noqa: E402

clf = DecisionTreeClassifier(max_depth=4, random_state=0)
clf.fit(fit[A.FEATURES], fit.implementation)
pred = clf.predict(hold[A.FEATURES])


def L(g, c, i):
    try:
        return lat.loc[(g, c, i)]
    except KeyError:
        return np.nan


chosen = np.array([L(g, c, i) for g, c, i
                   in zip(hold.gpu_name, hold.cell, pred)])
oracle = hold.median_us.values
hreg = hold.cell.str.split("|").str[0].values

w("A depth-4 decision tree over (cc, measured bandwidth, is_decode, log2 N, "
  "log2 B, head_dim, GQA ratio, is_bf16), **fit on %s and tested on the "
  "devices it never saw** (%s). The split is by hardware, not a random split "
  "of one grid, because the question is whether the rule transfers to an "
  "unseen GPU."
  % (" + ".join(sh(g) for g in sorted(fit.gpu_name.unique())),
     ", ".join(sh(g) for g in sorted(hold.gpu_name.unique()))))
w("")
w("**Lead with regret, not accuracy.** Accuracy asks whether the tree names "
  "the exact winner; regret asks what it costs when it does not. Several "
  "implementations sit within noise of each other in most cells, so accuracy "
  "understates the rule badly.")
w("")
table(["quantity", "value", "n"],
      [["**median regret** (selector latency / oracle latency)",
        "**%.4f** -- %.1f%% slower than a per-cell oracle"
        % (sel["median_regret"], 100 * (sel["median_regret"] - 1)),
        sel["n_heldout"]],
       ["**p95 regret**", "**%.3f**" % sel["p95_regret"], sel["n_heldout"]],
       ["oracle median latency", "%.1f us" % np.nanmedian(oracle),
        sel["n_heldout"]],
       ["selector median latency", "%.1f us" % np.nanmedian(chosen),
        "%d (%d cells have no latency for the predicted impl)"
        % (sel["n_heldout"], int(np.isnan(chosen).sum()))],
       ["top-1 accuracy", "%.1f%%" % (100 * sel["accuracy"]),
        sel["n_heldout"]],
       ["fit cells", len(fit), ", ".join(sh(g) for g in
                                         sorted(fit.gpu_name.unique()))],
       ["held-out cells", len(hold), ", ".join(sh(g) for g in
                                               sorted(hold.gpu_name.unique()))]])
w("Per regime, on the held-out devices:")
w("")
body = []
for r in ("prefill", "decode"):
    m = hreg == r
    body.append([r, int(m.sum()), "%.1f us" % np.nanmedian(oracle[m]),
                 "%.1f us" % np.nanmedian(chosen[m]),
                 "%.4f" % np.nanmedian(chosen[m] / oracle[m]),
                 "%.3f" % np.nanpercentile(chosen[m] / oracle[m], 95),
                 "%.1f%%" % (100 * (pred[m] == hold.implementation.values[m]).mean())])
table(["regime", "n cells", "oracle median", "selector median",
       "median regret", "p95 regret", "top-1 accuracy"], body)

body = []
for pol in sorted(set(cells.implementation)):
    fx = np.array([L(g, c, pol) for g, c in zip(hold.gpu_name, hold.cell)])
    covr = 1 - np.isnan(fx).mean()
    if covr <= 0.5:
        continue
    body.append([pol, "%.1f%%" % (100 * covr), int((~np.isnan(fx)).sum()),
                 "%.1f us" % np.nanmedian(fx),
                 "%.1f us" % np.nanmedian(np.where(np.isnan(fx), np.nan, chosen)),
                 "%.3fx" % np.nanmedian(fx / chosen),
                 "%.3fx" % np.nanpercentile(fx / chosen, 95)])
body.sort(key=lambda r: -float(r[5][:-1]))
n_dec_cov = int((hreg == "decode").sum()) / len(hold)
w("Against standing on one fixed implementation everywhere. **Every surviving "
  "policy is a prefill kernel**: the analysis drops any policy covering less "
  "than half the held-out cells, and the decode implementations reach only "
  "%.1f%%, so all of them were dropped. **This table is a prefill-only "
  "comparison and must be labelled as such.**" % (100 * n_dec_cov))
w("")
table(["fixed policy", "coverage of held-out cells", "n cells",
       "fixed median latency", "selector median latency on those cells",
       "median speedup", "p95 speedup"], body)
w("Read honestly: against the strongest fixed prefill policies the selector is "
  "a **wash at the median** (%s) and wins only in the tail. Its value is "
  "against the weak fixed policies and in never being catastrophically wrong. "
  "Never quote the largest speedup without naming the policy it beats and the "
  "absolute latencies on both sides."
  % ", ".join("%s %s" % (r[0], r[5]) for r in body
              if abs(float(r[5][:-1]) - 1) < 0.02))
w("")
w("Learned rule, verbatim, for the appendix:")
w("")
w("```")
w(sel["rule"].rstrip())
w("```")
w("")

# --------------------------------------------------------------------------- #
# 10. Stability
# --------------------------------------------------------------------------- #

w("## 10. Stability")
w("")
w("The unit of variation is the **per-process median**, not the individual "
  "rep: reps inside one process share clocks, allocator state and thermal "
  "point, so they are not independent draws. CV = std/mean over process "
  "repeats (ddof=1, five processes being a sample of the machine's "
  "process-to-process behaviour). Relative CI width = (hi - lo) / (2 x median) "
  "from a 2000-draw cluster bootstrap over process medians.")
w("")
st = stab.groupby(["gpu_name", "regime"]).agg(
    n=("cv", "size"), n_cv=("cv", "count"), med_cv=("cv", "median"),
    p95_cv=("cv", q(.95)), med_ci=("rel_ci_width", "median"),
    p95_ci=("rel_ci_width", q(.95)),
    med_rep=("n_repeats", "median")).reset_index()
table(["GPU", "regime", "triples", "triples with >1 process",
       "median process repeats", "median CV", "p95 CV",
       "median rel. CI width", "p95 rel. CI width"],
      [[sh(r.gpu_name), r.regime, r.n, r.n_cv, "%.0f" % r.med_rep,
        "%.4f" % r.med_cv, "%.4f" % r.p95_cv, "%.4f" % r.med_ci,
        "%.4f" % r.p95_ci] for r in st.itertuples()])
sg = stab.groupby("gpu_name").agg(
    n=("cv", "size"), n_cv=("cv", "count"), med_cv=("cv", "median"),
    p95_cv=("cv", q(.95)), med_ci=("rel_ci_width", "median"),
    p95_ci=("rel_ci_width", q(.95))).reset_index()
table(["GPU", "triples", "triples with >1 process", "median CV", "p95 CV",
       "median rel. CI width", "p95 rel. CI width"],
      [[sh(r.gpu_name), r.n, r.n_cv, "%.4f" % r.med_cv, "%.4f" % r.p95_cv,
        "%.4f" % r.med_ci, "%.4f" % r.p95_ci] for r in sg.itertuples()])

n1 = int((cells.reps == 1).sum())
w("**%d of %d usable triples have a single process repeat**, so they have no "
  "CV at all and a bootstrap CI of width 0. They are %d on A100 prefill, %d on "
  "L40S prefill and %d on L40 prefill. Any A100-prefill or L40S CI figure is "
  "dominated by these and is an artefact, not a precision measurement."
  % (n1, len(cells),
     int(((cells.reps == 1) & (cells.gpu_name == "NVIDIA A100-SXM4-80GB")).sum()),
     int(((cells.reps == 1) & (cells.gpu_name == "NVIDIA L40S")).sum()),
     int(((cells.reps == 1) & (cells.gpu_name == "NVIDIA L40")).sum())))
w("")
a10 = stab[stab.gpu_name == "NVIDIA A10"]
a100d = stab[(stab.gpu_name == "NVIDIA A100-SXM4-80GB")
             & (stab.regime == "decode")]
h100 = stab[stab.gpu_name == "NVIDIA H100 80GB HBM3"]
w("Safe headline, restricted to the device-regimes that genuinely have 5 "
  "process repeats: between-process CV is a median **%.4f** on A10 (n=%d "
  "triples), **%.4f** on A100 decode (n=%d) and **%.4f** on H100 (n=%d)."
  % (a10.cv.median(), len(a10), a100d.cv.median(), len(a100d),
     h100.cv.median(), len(h100)))
w("")
w("H100 is the noisiest device in the set at the tail -- p95 CV **%.3f** and "
  "p95 relative CI width **%.3f**, against %.3f and %.3f on A10. That tail is "
  "exactly what the %.2fx practical-inversion threshold exists to survive."
  % (h100.cv.quantile(.95), h100.rel_ci_width.quantile(.95),
     a10.cv.quantile(.95), a10.rel_ci_width.quantile(.95), PRACTICAL))
w("")

# --------------------------------------------------------------------------- #
# Not safe
# --------------------------------------------------------------------------- #

w("## NUMBERS THAT ARE NOT SAFE TO QUOTE YET")
w("")
w("### A. Claims carried in the project notes that this dataset does not support")
w("")
n_fi_ok = int(((rows.implementation == "D4-flashinfer")
               & (rows.status == "OK")).sum())
n_fi_oom = int(((rows.implementation == "D4-flashinfer")
                & (rows.status == "OOM")).sum())
table(["claim as carried in the notes", "status against `results/processed/`"],
      [["RTX 5090 / sm120 as a fifth compute-capability target",
        "**No sm120 rows exist.** `rows.parquet` holds %d devices: %s -- %d "
        "compute capabilities across 3 architecture families (Ampere, Ada, "
        "Hopper). No Blackwell sentence is supported here."
        % (len(GPUS),
           ", ".join("%s (%d.%d)" % (sh(g), env[g]["cc_major"],
                                     env[g]["cc_minor"]) for g in GPUS),
           len({(env[g]["cc_major"], env[g]["cc_minor"]) for g in GPUS}))],
       ["'FlashInfer cannot run on sm120: 950 ERROR of 960 cells'",
        "**No ERROR rows exist anywhere** (the only statuses present are "
        "OK/UNSUPPORTED/OOM_PREDICTED/OOM) and there is no sm120 device. "
        "D4-flashinfer is OK on %d rows and OOM on %d. The "
        "nvcc-12.8-cannot-target-Blackwell finding is not reproducible from "
        "this data." % (n_fi_ok, n_fi_oom)],
       ["NUMA pinning: between-process CV 0.112 -> 0.034, configs disagreeing "
        ">25% 30.7% -> 9.9%, 3-GPU flip rate 58.1% -> 63.9%",
        "**Not derivable here.** `results_h100_unpinned/` holds `raw/` and "
        "`environment/` but **no `processed/`**, so there is no unpinned "
        "parquet to compare against. Run `python -m akp.analysis "
        "results_h100_unpinned/raw` before quoting any of these."],
       ["Binary provenance: flash-attn 2.8.3 ships SASS for sm_80/90/100/120 "
        "and no PTX; `libtorch_cuda` alone carries native sm_89",
        "**Not in `results/processed/`.** `scripts/provenance.sh` exists but "
        "deposits nothing here. The claim may well hold; it is not one of "
        "*these* numbers, and needs its own committed cuobjdump artefact."],
       ["Nsight Compute / Nsight Systems counters",
        "**None exist.** `analysis.nsight()` finds no "
        "`results/profile/*/ncu.csv`. No occupancy, cache-hit-rate, or "
        "counter-derived roofline claim can be made."],
       ["'FlashInfer is the decode winner on A10 128, A100 133, H100 113 "
        "configs'",
        "A10 %d and A100 %d reproduce; **H100 is %d, not 113** -- the H100 "
        "decode grid grew to %d cells. Re-derive before quoting."
        % (int(((W.gpu_name == "NVIDIA A10")
                & (W.implementation == "D4-flashinfer")).sum()),
           int(((W.gpu_name == "NVIDIA A100-SXM4-80GB")
                & (W.implementation == "D4-flashinfer")).sum()),
           int(((W.gpu_name == "NVIDIA H100 80GB HBM3")
                & (W.implementation == "D4-flashinfer")).sum()),
           int(((W.gpu_name == "NVIDIA H100 80GB HBM3")
                & (W.regime == "decode")).sum()))],
       ["'`fuse_attention` is 0 on all 1215 inductor rows'",
        "The finding holds but **the n has grown to %d** rows with a captured "
        "counter (of %d inductor rows total). Quote %d."
        % (len(indok), len(ind), len(indok))]])

w("### B. Present in the data but too thin, confounded, or measuring something "
  "other than what the sentence says")
w("")
table(["number", "why it is not safe as written", "n"],
      [["All-5-device winner-flip rate (%.1f%%)" % (100 * f_all),
        "Only %d cells are shared by all five devices and **every one of them "
        "is prefill** (L40S ran no decode). It is also not comparable with the "
        "3-device %.1f%%: more devices raises the rate mechanically. Quote it "
        "only as 'prefill, 5 devices, n=%d'." % (n_all, 100 * f_tp, n_all),
        "%d cells%s" % (n_all, thin(n_all))],
       ["Any decode cross-GPU comparison involving A10 or A100",
        "**Confounded with a commit and driver change.** A10 and A100 decode "
        "rows are *all* at git `468b9a55`; H100 and L40 decode rows are *all* "
        "at `91959d34`, recorded days later, with different manifest drivers "
        "(595.71.05 / 580.126.09 / 610.43.02). Architecture and software "
        "version move together, so the %.1f%% decode flip rate cannot be "
        "attributed to hardware. **Prefill is clean** -- all five devices ran "
        "prefill at `91959d34`, so the %.1f%% prefill flip rate is not "
        "confounded this way." % (100 * f_td, 100 * f_ah),
        "191-244 decode cells per device"],
       ["Anything about A100 prefill",
        "%d rows at **%d process repeats**, %.0f%% grid completeness, and %d "
        "of its %d usable *prefill* triples are single-process -- so its "
        "median relative CI width reads 0.0000 as an artefact of having "
        "nothing to bootstrap."
        % (int(t.set_index(["gpu_name", "regime"])
               .n_rows[("NVIDIA A100-SXM4-80GB", "prefill")]),
           reps[("NVIDIA A100-SXM4-80GB", "prefill")],
           100 * t.set_index(["gpu_name", "regime"])
           .completeness[("NVIDIA A100-SXM4-80GB", "prefill")],
           int(((cells.reps == 1) & (cells.regime == "prefill")
                & (cells.gpu_name == "NVIDIA A100-SXM4-80GB")).sum()),
           int(((cells.regime == "prefill")
                & (cells.gpu_name == "NVIDIA A100-SXM4-80GB")).sum())),
        "108 cells"],
       ["Anything about L40S standalone",
        "Prefill only, %d process repeats, %d of %d prefill cells, %d of %d "
        "usable triples single-process. Sound as the L40 twin control; not a "
        "standalone device result."
        % (reps[("NVIDIA L40S", "prefill")],
           int(t.set_index(["gpu_name", "regime"])
               .n_cells[("NVIDIA L40S", "prefill")]), union["prefill"],
           int(((cells.reps == 1) & (cells.gpu_name == "NVIDIA L40S")).sum()),
           int((cells.gpu_name == "NVIDIA L40S").sum())),
        "101 cells"],
       ["L40 decode bandwidth utilisation (median %.3f)" % bw.med["NVIDIA L40"],
        "Exceeds 1.0, so the measured-peak probe under-reads L40 rather than "
        "the kernels exceeding hardware. The ratio is not a utilisation. Quote "
        "effective GB/s, or re-measure peak bandwidth on that part.",
        "%d rows" % int(bw.n["NVIDIA L40"])],
       ["Cold-L2 cache sensitivity",
        "**%s only**, %d paired measurements, median sensitivity %.3f -- i.e. "
        "cold measures *faster* than warm, which is a pairing artefact, not a "
        "result. No other device produced a cold/warm pair at a matching "
        "`inner_k`."
        % (", ".join(sh(g) for g in sorted(cs.gpu_name.unique())),
           int(cs.sensitivity.notna().sum()), cs.sensitivity.median()),
        "%d pairs%s" % (int(cs.sensitivity.notna().sum()),
                        thin(int(cs.sensitivity.notna().sum())))],
       ["Selector 'vs fixed policy' speedups",
        "Prefill-only by construction: the >50%% coverage filter drops every "
        "decode policy at %.1f%%. Against the two strongest fixed prefill "
        "policies the median speedup is %s. Never quote the headline speedup "
        "without naming the policy and both absolute latencies."
        % (100 * n_dec_cov,
           " and ".join(r[5] for r in body[-2:]) if len(body) >= 2 else "n/a"),
        "%s held-out cells" % body[0][2] if body else "n/a"],
       ["H100 decode latencies below ~25 us",
        "H100's event overhead is %.3f us and its fastest usable cell is "
        "%.2f us -- **%.1fx overhead**. %d of %d H100 triples sit within 5x of "
        "the timer. The fastest of them (%s, `%s`) is also a winner cell, so "
        "at the small-B, small-N, cudagraph end the winner margin is competing "
        "with timer resolution. Report those cells with the overhead beside "
        "them or exclude them."
        % (env["NVIDIA H100 80GB HBM3"]["event_overhead_us"],
           cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"].median_us.min(),
           cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"].median_us.min()
           / env["NVIDIA H100 80GB HBM3"]["event_overhead_us"],
           int((cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"].median_us
                < 5 * env["NVIDIA H100 80GB HBM3"]["event_overhead_us"]).sum()),
           int((cells.gpu_name == "NVIDIA H100 80GB HBM3").sum()),
           cells.loc[cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"]
                     .median_us.idxmin()].implementation,
           cells.loc[cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"]
                     .median_us.idxmin()].cell),
        "%d triples" % int((cells[cells.gpu_name == "NVIDIA H100 80GB HBM3"]
                            .median_us
                            < 5 * env["NVIDIA H100 80GB HBM3"]
                            ["event_overhead_us"]).sum())],
       ["Selector top-1 accuracy (%.1f%%)" % (100 * sel["accuracy"]),
        "Reads as a failure but is not the quantity of interest -- median "
        "regret is %.3f. Lead with regret; if accuracy appears at all, put "
        "regret beside it." % sel["median_regret"],
        "%d held-out cells" % sel["n_heldout"]],
       ["'torch.compile does not rewrite naive attention into SDPA'",
        "The **counter** claim is solid (0 on %d rows). The stronger claim is "
        "not: %d probed inductor rows on H100 do carry a flash kernel in the "
        "trace. Say 'Inductor's `fuse_attention` counter never fired'."
        % (len(indok), len(t45)), "%d rows" % len(indok)],
       ["Dispatch mismatch rate",
        "%.3f%% among probed rows but %.3f%% over all audited rows -- state "
        "the denominator. %.1f%% of OK rows were never probed, so the rate on "
        "unprobed rows is **unknown**, not zero."
        % (100 * mism / len(pr), 100 * mism / len(da),
           100 * (~da.probed).mean()),
        "%d probed of %d" % (len(pr), len(da))],
       ["Spread quoted as a cross-regime ratio",
        "Prefill %.1fx against decode %.2fx compares different implementation "
        "sets (10 vs 6) over different cells and different lengths. It is a "
        "statement about how much the *choice* matters per regime, not about "
        "any kernel's speed."
        % (byr["median"]["prefill"], byr["median"]["decode"]),
        "%d / %d device-cell pairs" % (int(byr.n["prefill"]),
                                       int(byr.n["decode"]))],
       ["Any pairwise inversion rate at or below the same-architecture floor",
        "The L40 vs L40S control already shows %.2f%% practical inversions at "
        "Spearman %.3f. %s sits at or below that floor and is therefore not "
        "evidence of architectural disagreement. The floor is calibrated on "
        "prefill only, so decode has no established floor at all."
        % (100 * ctl["practical"] / ctl["pairs"], ctl["spearman"],
           ", ".join("%s vs %s (%.2f%%)" % (sh(a), sh(b),
                                            100 * d["practical"] / d["pairs"])
                     for a, b, d in below) or "No other pair"),
        "%d impl pairs (control)" % ctl["pairs"]]])

w("### C. Wording discipline these numbers do not license")
w("")
w("- **FlashAttention does not remove quadratic FLOPs.** Nothing here measures "
  "arithmetic; the `tflops` column is an *algorithmic* FLOP count divided by "
  "measured time. FA reduces materialisation and memory traffic -- exact "
  "attention still does quadratic arithmetic.")
w("- Every claim is scoped to a **(kernel, GPU, regime, "
  "software-distribution snapshot)**. Exactly one torch / flash-attn / "
  "flashinfer combination was measured; a different wheel is a different "
  "experiment, not a replication.")
w("- The packaging hypothesis -- that sm_86 and sm_89 devices execute sm_80 "
  "cubins under CUDA minor-version binary compatibility -- is **consistent "
  "with** the pattern of P4-fa2 wins and losses. No rebuild was performed, so "
  "it is not shown to **cause** anything, and the provenance artefact backing "
  "it is not in this directory (section A).")
w("- **No speedup appears in this document without its absolute latency**, and "
  "none should appear in the paper without one either.")
w("- A winner-flip rate is meaningless without its **n_gpus and n_cells**. "
  "Rates from different device counts are not comparable.")
w("")

out = os.path.join(ROOT, "paper", "numbers.md")
text = "\n".join(O) + "\n"
open(out, "w", encoding="utf8").write(text)
print("wrote %s (%d lines, %d chars)" % (out, len(O), len(text)))
